plugins {
    id "com.android.application"
}

android {
    namespace "com.oc11.purchase"
    compileSdk 35

    defaultConfig {
        applicationId "com.oc11.purchase"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "1.0.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
